openapi: 3.0.3
info:
  title: Bermaro Plenty API Proxy
  version: 1.0.0
servers:
  - url: https://plenty-chat-api-1032467933623.europe-west1.run.app
paths:
  /order:
    get:
      summary: Get order by ID
      operationId: getOrder
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
  /tracking:
    get:
      summary: Get tracking by order ID
      operationId: getTracking
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tracking details
  /article:
    get:
      summary: Get article by ID
      operationId: getArticle
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Article details
