openapi: 3.0.3
info:
  title: Bermaro Plenty API Proxy
  version: 1.0.0
servers:
  - url: https://8080-cs-494f5ed1-8b64-47f0-a33c-d86c48bf1cae.cs-europe-west1-iuzs.cloudshell.dev
paths:
  /order:
    get:
      summary: Get order by ID
      operationId: getOrder
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        '200':
          description: Successful response
  /tracking:
    get:
      summary: Get tracking by Order ID
      operationId: getTracking
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        '200':
          description: Successful response
